### ISSUE TITLE
I have got this erros when trying to test your model. I have followed the path to create the manifest.csv

### ISSUE THREAD

**Issue by navarmn** [igormq/aes-lac-2018#2]
Traceback (most recent call last):
  File "test.py", line 49, in <module>
    dataset = AudioDataset(args.data_dir, args.manifest, transforms=transforms, target_transforms=target_transforms)
  File "/workspace/codes/data.py", line 30, in __init__
    if zipfile.is_zipfile(self.data_dir):
  File "/opt/conda/lib/python3.7/zipfile.py", line 180, in is_zipfile
    with open(filename, "rb") as fp:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by igormq** [comment]
It seems that you are not setting correctly the flag --data-dir. :)
