### ISSUE TITLE
IndexError: too many indices for array - train.py for the finetunemodel

### ISSUE THREAD

**Issue by navarmn** [igormq/aes-lac-2018#4]
Traceback (most recent call last):
  File "train.py", line 401, in <module>
    trainer.run(train_loader, args.config.training.num_epochs)
  File "/home/navar/anaconda3/lib/python3.6/site-packages/pytorch_ignite-0.1.1-py3.6.egg/ignite/engine/engine.py", line 326, in run
  File "/home/navar/anaconda3/lib/python3.6/site-packages/pytorch_ignite-0.1.1-py3.6.egg/ignite/engine/engine.py", line 291, in _handle_exception
  File "/home/navar/anaconda3/lib/python3.6/site-packages/pytorch_ignite-0.1.1-py3.6.egg/ignite/engine/engine.py", line 313, in run
  File "/home/navar/anaconda3/lib/python3.6/site-packages/pytorch_ignite-0.1.1-py3.6.egg/ignite/engine/engine.py", line 280, in _run_once_on_dataset
  File "/home/navar/anaconda3/lib/python3.6/site-packages/pytorch_ignite-0.1.1-py3.6.egg/ignite/engine/engine.py", line 291, in _handle_exception
  File "/home/navar/anaconda3/lib/python3.6/site-packages/pytorch_ignite-0.1.1-py3.6.egg/ignite/engine/engine.py", line 268, in _run_once_on_dataset
  File "/home/navar/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/navar/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/navar/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/navar/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/mnt/Work/Projects/2018-Locktec-SAVOZ/general/aes-lac-2018-master/codes/data.py", line 65, in __getitem__
    target = self.target_transforms(target)
  File "/mnt/Work/Projects/2018-Locktec-SAVOZ/general/aes-lac-2018-master/codes/transforms.py", line 382, in __call__
    return labels[:, np.newaxis]
IndexError: too many indices for array

**Comment by avdcc** [comment]
Where you able to solve this error? I am having the same problem

**Comment by navarmn** [comment]
I guess i have found a Turnaround. It is been a while since a used this
repo. Let me take a look.

Em ter, 3 de dez de 2019 09:58, Adriano Campinho <notifications@github.com>
escreveu:
