### ISSUE TITLE
python3 train.py scripts/pt_BR-finetune.json - not working

### ISSUE THREAD

**Issue by navarmn** [igormq/aes-lac-2018#5]
Traceback (most recent call last):
  File "train.py", line 402, in <module>
    trainer.run(train_loader, args.config.training.num_epochs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_ignite-0.1.2-py3.6.egg/ignite/engine/engine.py", line 326, in run
  File "/usr/local/lib/python3.6/dist-packages/pytorch_ignite-0.1.2-py3.6.egg/ignite/engine/engine.py", line 291, in _handle_exception
  File "/usr/local/lib/python3.6/dist-packages/pytorch_ignite-0.1.2-py3.6.egg/ignite/engine/engine.py", line 313, in run
  File "/usr/local/lib/python3.6/dist-packages/pytorch_ignite-0.1.2-py3.6.egg/ignite/engine/engine.py", line 280, in _run_once_on_dataset
  File "/usr/local/lib/python3.6/dist-packages/pytorch_ignite-0.1.2-py3.6.egg/ignite/engine/engine.py", line 291, in _handle_exception
  File "/usr/local/lib/python3.6/dist-packages/pytorch_ignite-0.1.2-py3.6.egg/ignite/engine/engine.py", line 272, in _run_once_on_dataset
  File "/home/navar/savoz/aes-lac-2018/codes/engine.py", line 48, in _update
    LOG.DEBUG(engine.state.iteration)
AttributeError: 'Logger' object has no attribute 'DEBUG'

**Comment by navarmn** [comment]
I realized the field "finetune" in the scripts/pt_BR-finetune.json was set to **false**. When I set to true I was able to retrain the model. Should I make a PR?
