### ISSUE TITLE
KeyError: 'lang' - in python train.py scripts/pt_BR-finetune.json 

### ISSUE THREAD

**Issue by navarmn** [igormq/aes-lac-2018#6]
Traceback (most recent call last):
  File "train.py", line 167, in <module>
    model = tu.finetune_model(model, args.config.model)
  File "/home/navar/savoz/aes-lac-2018/codes/utils/training_utils.py", line 90, in finetune_model
    num_classes = NUM_CLASSES[obj['lang']]
KeyError: 'lang'

**Comment by navarmn** [comment]
I just found the line 89 in she training_utils.py is writen as `num_classes = NUM_CLASSES[obj['lang']]` and it change to fixed the bug:

`num_classes = NUM_CLASSES[obj['langs'][0]]`

Should I make a PR?
